version: '3.7'
services:
  eventmodeling-eventstore-dotnet:
    container_name: eventmodeling-eventstore-dotnet
    image: eventstore/eventstore:21.2.0-buster-slim
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISABLE_HTTP_CACHING=false
      - EVENTSTORE_DEV=true
    ports:
      - "1113:1113"
      - "2113:2113"
