version: '3.7'
services:
  eventmodeling-build-eventstore:
    container_name: eventmodeling-build-eventstore
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
  eventmodeling-build-frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventmodeling-build-frontend-react
    ports:
      - 3000:3000
  eventmodeling-build-backend-nodejs:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    container_name: eventmodeling-build-backend-nodejs
    ports:
      - 4000:4000
    environment:
      EVENTSTORE_CONNECTION_STRING: esdb://eventmodeling-build-eventstore:2113?tls=false
    depends_on:
      - eventmodeling-build-eventstore
      - eventmodeling-build-backend-dotnet
      - eventmodeling-build-backend-kotlin
  eventmodeling-build-backend-dotnet:
    build:
      context: ./backend-dotnet/EventModelingGitHubCloneDotNet
      dockerfile: Dockerfile
    container_name: eventmodeling-build-backend-dotnet
    environment:
      ASPNETCORE_URLS: http://+:5000
      EVENTSTORE_CONNECTION_STRING: esdb://eventmodeling-build-eventstore:2113?tls=false
      CLOCK: SYSTEM
      ALLOW_MERGING_SERVICE_URL: http://eventmodeling-build-backend-nodejs:4000/rest-api
      DISALLOW_MERGING_SERVICE_URL: http://eventmodeling-build-backend-nodejs:4000/rest-api
    ports:
      - 5000:5000
    depends_on:
      - eventmodeling-build-eventstore
  eventmodeling-build-backend-kotlin:
    build:
      context: ./backend-kotlin
      dockerfile: Dockerfile
    container_name: eventmodeling-build-backend-kotlin
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EVENTSTORE_CONNECTION_STRING: esdb://eventmodeling-build-eventstore:2113?tls=false
    ports:
      - 7000:7000
    depends_on:
      - eventmodeling-build-eventstore
